
# This is a basic workflow to help you get started with Actions

name: MTurk

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- name: Set up Python 3.8
       # uses: actions/setup-python@v2
       # with:
       #   python-version: '3.8'
        
      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: |
          pip install -r mturk_only_requirements.txt
          
      # Runs a set of commands using the runners shell
      - name: Gets MTurk Files
        run: dvc repro modeling/dvc.yaml:mturk

      # Push Updates to Repo
      - name: Git Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "New MTurk Results"
          git push
